# ==================API USER================ 
### Sign up
POST http://localhost:3005/users/create
Content-Type: application/json

# data: {
#     email: string,
#     username: string,
#     password: string
# }

# Sample data
{
    "email": "chungdi@gmail.com",
    "username": "chungdi",
    "password": "123456789"
}

### Login
POST http://localhost:3005/users/login
Content-Type: application/json

# data: {
#     email: string,
#     password: string
# }

# Sample data
{
    "email": "chungdi@gmail.com",
    "password": "123456789"
}

# ====================API ALBUM===================
### Create album
POST http://localhost:3005/albums/create
Content-Type: application/json

# data: {
#     data: string,
#     image: File
# }

# Sample data
{
    "data": "{'title':'chungdi','description':'sdfsdfoioi'}",
    "image": "File"
}

### Find all albums
GET http://localhost:3005/albums

### Find all song by all album
GET http://localhost:3005/albums/song-by-album

### Find all song by one album
GET http://localhost:3005/albums/song-by-album/6421e55f65e79c34f1acde1c

# sample id
# [
#     "6421e55f65e79c34f1acde19",
#     "6421e55f65e79c34f1acde1a",
#     "6421e55f65e79c34f1acde1b",
#     "6421e55f65e79c34f1acde1c"
# ]

# ====================API SONGS===================
### Create song
POST http://localhost:3005/songs/create
Content-Type: application/json

# data: {
#     data: string,
#     thumb_nail: File,
#     audio: File
# }

# Sample data
# ! album_id and genre is an array
{
    "data": {
        "album_id": [1], 
        "name": "Meo meo meo",
        "artist": "Amee",
        "genre": ["balad"]
    },
    "thumb_nail": "File",
    "audio": "File"
}