# ==================API USER================ 
### Sign up
POST http://localhost:3005/users/create
Content-Type: application/json

# data: {
#     email: string,
#     username: string,
#     password: string
# }

# Sample data
{
    "email": "chungdi@gmail.com",
    "username": "chungdi",
    "password": "123456789"
}

### Login
POST http://localhost:3005/users/login
Content-Type: application/json

# data: {
#     email: string,
#     password: string
# }

# Sample data
{
    "email": "chungdigmail.com",
    "password": "1234555789"
}

# ====================API ALBUM===================
### Create album
POST http://localhost:3005/albums/create
Content-Type: application/json

# data: {
#     data: string,
#     image: File
# }

# Sample data
{
    "data": "{'title':'chungdi','description':'sdfsdfoioi'}",
    "image": "File"
}
{
    "title": "helle",
    "description": "alo alo",
}

### Find all albums
GET http://localhost:3005/albums